# Generated by Django 2.2.10 on 2020-09-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cookie',
            field=models.CharField(default='nom', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='playergameinfo',
            unique_together={('player', 'game')},
        ),
    ]
