# Generated by Django 2.2.10 on 2020-09-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200903_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='cookie',
        ),
        migrations.RemoveField(
            model_name='playergameinfo',
            name='victor',
        ),
        migrations.AddField(
            model_name='game',
            name='final_tries',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='session_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='last_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='tries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='ongoing',
            field=models.BooleanField(default=True),
        ),
    ]
